# Tutorial to use with: https://github.com/andry81-devops/accum-content
#

name: "andry81: content update at least every 6 hours"

on:
  schedule:
    - cron: "0 */6 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      # for tests
      no_skip_unexpired_entries:
        description: 'Do not skip unexpired entries'
        required: false
        default: 'false'
      no_download_entries:
        description: 'Do not download entries'
        required: false
        default: 'false'

jobs:
  accum-content-cache:
    runs-on: ubuntu-latest

    steps:
      - uses: andry81-devops/gh-action--accum-content@master
        with:
          deps_repo_owner:          andry81-devops
          deps_repo_branch:         master
          deps_repo_read_token:     ${{ github.token }}

          config_repo_owner:        andry81-cache
          config_repo:              gh-content-cache-config
          config_repo_branch:       master
          config_repo_read_token:   ${{ secrets.READ_STATS_TOKEN }}

          store_repo_owner:         andry81-cache
          store_repo:               andry81--gh-content-cache
          store_repo_branch:        master
          store_repo_write_token:   ${{ secrets.READ_STATS_TOKEN }}

          commit_msg_entity:        andry81

          # config repo
          content_config_file:      repo/andry81/andry81/content-config.yml

          # store repo
          content_index_file:       repo/andry81/andry81/content-index.yml

          content_index_dir:        repo/andry81/andry81

          curl_flags: >-
            -H 'Cache-Control: no-cache'
            -v

          flags: >-
            ENABLE_PRINT_INITIAL_ENV_INTO_STDOUT=1

          env: >-
            ENABLE_GENERATE_CHANGELOG_FILE=1
            CHANGELOG_FILE=repo/andry81/andry81/content-changelog.txt
            ENABLE_COMMIT_MESSAGE_DATE_WITH_TIME=1
            ENABLE_COMMIT_MESSAGE_WITH_WORKFLOW_RUN_NUMBER=1
            ENABLE_YAML_DIFF_PRINT_AFTER_EDIT=1
            ENABLE_YAML_DIFF_PRINT_BEFORE_PATCH=1
            ENABLE_GITHUB_ACTIONS_RUN_URL_PRINT_TO_CHANGELOG=1
            ENABLE_REPO_STORE_COMMITS_URL_PRINT_TO_CHANGELOG=1
            CONTINUE_ON_EMPTY_CHANGES=1
            ERROR_ON_EMPTY_CHANGES_WITHOUT_ERRORS=1
          #  "USE_APT_GET_INSTALL_CMDLINE=-y xmlstarlet"
          #  "USE_PYTHON3_PIP_INSTALL_CMDLINE=xq"
