# Tutorial to use with: https://github.com/andry81-devops/github-accum-stats
#

name: "tacklebar: totalcmd plugin downloads update every 4 hours"

on:
  schedule:
    - cron: "0 */4 * * *"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  accum-totalcmd-plugin-downloads:
    runs-on: ubuntu-latest

    steps:
      - uses: andry81-devops/gh-action--accum-inpage-downloads@master
        with:
          # CAUTION: Beware of double quotes strip in case of usage yaml `>-` operator or even a single-quotted string!
          query_url:                http://totalcmd.net/plugring/tacklebar.html
          downloads_sed_regexp:     s/.*Downloaded:[^0-9]*([0-9.]+).*/\1/p

          curl_flags: >-
            -v
            -H 'Cache-Control: no-cache'

          deps_repo_owner:          andry81-devops
          deps_repo_branch:         master
          deps_repo_read_token:     ${{ github.token }}

          commit_msg_entity:        tacklebar

          output_repo_owner:        andry81-stats
          output_repo:              tacklebar--totalcmd-stats
          output_repo_branch:       master
          output_repo_dir:          traffic/downloads/plugin
          output_repo_write_token:  ${{ secrets.READ_STATS_TOKEN }}

          flags: >-
            ENABLE_PRINT_INITIAL_ENV_INTO_STDOUT=1

          env: >-
            ENABLE_GENERATE_CHANGELOG_FILE=1
            ENABLE_PRINT_CURL_RESPONSE_ON_ERROR=1
            ENABLE_COMMIT_MESSAGE_DATE_WITH_TIME=1
            ENABLE_COMMIT_MESSAGE_WITH_WORKFLOW_RUN_NUMBER=1
            ENABLE_GITHUB_ACTIONS_RUN_URL_PRINT_TO_CHANGELOG=1
            ENABLE_REPO_STATS_COMMITS_URL_PRINT_TO_CHANGELOG=1
